name: API CI checks

on:
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  lint:
    name: Lint API
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: rkulinski/offboarding/.github/workflows/api_setup.yml@main
      - name: Run ESLint
        working-directory: ./api
        run: npm run lint

  test:
    name: Test API
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: rkulinski/offboarding/.github/workflows/api_setup.yml@main
      - name: Run Tests
        working-directory: ./api
        env:
          NODE_ENV: test
        run: npm test
